
import { SelectOption } from './types';

// PERSISTENCE KEYS
export const STORAGE_KEYS = {
  AVATAR_STATE: "mlaos_nexus_avatar_state_v1",
};

// RITUAL SKIN ENGINE CONSTANTS
export const RITUAL_SKIN_PRESETS = [
  "None",
  "Etched Glyph Traces",
  "Firefall Fracture Veins",
  "Choir Brand: Gold Θ",
  "Choir Brand: Teal Ψ",
  "Choir Brand: Blue Δ",
  "Choir Brand: Red Φ",
  "Choir Brand: Violet Ω",
  "Choir Brand: Emerald Ε",
  "Null Asema Sigils",
  "Bioluminescent Veins",
  "Metallic Subdermal Lattice",
  "Void-Touched Scars"
];

export const RITUAL_SKIN_LOCI = [
  "Subtle traces along forearms",
  "Spine column as glowing script",
  "Face: faint halo-markings",
  "Chest: central invocation seal",
  "Hands and fingers only",
  "Full-body lattice (low intensity)",
  "Asymmetrical (Left Side)",
  "Throat and Jawline"
];

// PLACEHOLDER CONSTANTS FOR FUTURE ORGANS
export const CATHEDRAL_BODY_ARCHETYPES = [
  "Default Humanoid (placeholder)",
  "Cathedral-Born Frame (placeholder)",
  "Vaultwalker Ligament Scaffold (placeholder)",
];

export const METAMORPH_STATES = [
  "Stable (placeholder)",
  "Pre-Ignition (placeholder)",
  "Firefall Surge (placeholder)",
  "Crystal Transparent Memory (placeholder)",
];

export const RACES: SelectOption[] = [
  { label: 'Human (Cathedral Born)', value: 'Human' },
  { label: 'High Elf (Orthodox)', value: 'High Elf' },
  { label: 'Dark Elf (Taboo)', value: 'Dark Elf' },
  { label: 'Construct (Porcelain)', value: 'Porcelain Construct' },
  { label: 'Tiefling (Diabolic)', value: 'Tiefling' },
  { label: 'Aasimar (Angelic)', value: 'Aasimar' },
  { label: 'Vampire (Sanguine)', value: 'Vampire' },
  { label: 'Kitsune (Spirit)', value: 'Kitsune' },
  { label: 'Ethereal Spirit', value: 'Ethereal Spirit' },
  { label: 'Void-Touched', value: 'Void-Touched Entity' },
  // ORIGINAL EXPANSION
  { label: 'Glass-Walker (Silicate)', value: 'Living Stained-Glass Entity' },
  { label: 'Echo-Bound (Sonic)', value: 'Resonant Soundwave Entity' },
  { label: 'Fractal-Kin (Geometry)', value: 'Non-Euclidean Geometric Being' },
  { label: 'Lumen-Symbiote', value: 'Human host to a Light-Parasite' },
];

export const CLASSES: SelectOption[] = [
  { label: 'Lantern Witch', value: 'Lantern Witch' },
  { label: 'Cathedral Librarian', value: 'Cathedral Librarian' },
  { label: 'Stargazer Sorceress', value: 'Stargazer Sorceress' },
  { label: 'Etiquette Adept', value: 'Taboo Etiquette Adept' },
  { label: 'Choir Conductor', value: 'Choir Conductor' },
  { label: 'Void Navigator', value: 'Void Navigator' },
  { label: 'Relic Keeper', value: 'Relic Keeper' },
  { label: 'Silent Knight', value: 'Silent Knight' },
  { label: 'Glass Dancer', value: 'Glass Dancer' },
  { label: 'Memory Weaver', value: 'Memory Weaver' },
  // ORIGINAL EXPANSION
  { label: 'Resonance Architect', value: 'Resonance Architect (Sound-Shaper)' },
  { label: 'Prism-Sentinel', value: 'Prism-Sentinel (Light-Guard)' },
  { label: 'Entropy-Gardener', value: 'Entropy-Gardener' },
  { label: 'Geometry-Monk', value: 'Sacred Geometry Monk' },
  { label: 'Echo-Assassin', value: 'Echo-Assassin' },
];

export const SKIN_TONES: SelectOption[] = [
  { label: 'Porcelain Pale', value: 'porcelain pale skin' },
  { label: 'Obsidian Dark', value: 'obsidian dark skin' },
  { label: 'Bronze', value: 'polished bronze skin' },
  { label: 'Translucent', value: 'semi-translucent skin' },
  { label: 'Vampiric White', value: 'dead white skin' },
  { label: 'Void-Stained', value: 'gray skin with black veins' },
  { label: 'Gold-Dust', value: 'skin covered in gold dust' },
  { label: 'Ethereal Blue', value: 'pale blue skin' },
  { label: 'Olive', value: 'olive skin' },
  { label: 'Deep Brown', value: 'deep brown skin' },
];

export const HAIR_STYLES: SelectOption[] = [
  { label: 'Floor-Length Flowing', value: 'very long, loose and flowing hair' },
  { label: 'Braided Crown', value: 'intricate braided crown' },
  { label: 'Floating (Zero-G)', value: 'hair floating in zero gravity' },
  { label: 'Shaved / Bald', value: 'completely shaved head' },
  { label: 'Bob Cut', value: 'sharp bob cut' },
  { label: 'Wild / Feral', value: 'wild, unkempt mane' },
  { label: 'Pixie Cut', value: 'short pixie cut' },
];

export const COLORS: SelectOption[] = [
  { label: 'Void Black', value: 'Void Black' },
  { label: 'Starlight White', value: 'Starlight White' },
  { label: 'Crimson Red', value: 'Crimson Red' },
  { label: 'Royal Gold', value: 'Royal Gold' },
  { label: 'Emerald Green', value: 'Emerald Green' },
  { label: 'Midnight Blue', value: 'Midnight Blue' },
  { label: 'Amethyst Purple', value: 'Amethyst Purple' },
  { label: 'Silver', value: 'Polished Silver' },
  { label: 'Copper', value: 'Oxidized Copper' },
  { label: 'Teal', value: 'Bioluminescent Teal' },
];

export const EYE_COLORS: SelectOption[] = [
  { label: 'Glowing White', value: 'glowing white' },
  { label: 'Void Black (No Sclera)', value: 'solid black eyes with no sclera' },
  { label: 'Piercing Blue', value: 'piercing ice blue' },
  { label: 'Emerald Green', value: 'glowing emerald green' },
  { label: 'Molten Gold', value: 'molten gold' },
  { label: 'Violet', value: 'deep violet' },
  { label: 'Blind / Milky', value: 'milky white blind eyes' },
  { label: 'Red', value: 'glowing crimson red' },
];

export const ATTIRE_TOPS: SelectOption[] = [
  { label: 'Ritual Robes', value: 'Ritual Robes' },
  { label: 'Plate Armor', value: 'Ornate Plate Armor' },
  { label: 'Corset', value: 'Tight Leather Corset' },
  { label: 'Silk Blouse', value: 'Sheer Silk Blouse' },
  { label: 'Bandages', value: 'Wrapped Ritual Bandages' },
  { label: 'Nothing (Taboo)', value: 'Bare Chest with Jewelry' },
];

export const ATTIRE_BOTTOMS: SelectOption[] = [
  { label: 'Flowing Train', value: 'Long Flowing Train' },
  { label: 'Armored Greaves', value: 'Heavy Armored Greaves' },
  { label: 'Silk Skirt', value: 'Layered Silk Skirt' },
  { label: 'Leather Pants', value: 'Tight Leather Pants' },
  { label: 'Loincloth', value: 'Ceremonial Loincloth' },
];

export const ATTIRE_OUTER: SelectOption[] = [
  { label: 'No Outer Layer', value: 'no outer layer' },
  { label: 'Glass-Silk Cape', value: 'Glass-Silk Cape' },
  { label: 'Heavy Fur Mantle', value: 'Heavy Fur Mantle' },
  { label: 'Feathered Wings', value: 'Large Feathered Wings' },
  { label: 'Tatters', value: 'Floating Tattered Cloth' },
  { label: 'Hooded Cloak', value: 'Deep Hooded Cloak' },
];

export const FOOTWEAR: SelectOption[] = [
  { label: 'Barefoot', value: 'Barefoot' },
  { label: 'Armored Boots', value: 'Heavy Plate Boots' },
  { label: 'Silk Slippers', value: 'Delicate Silk Slippers' },
  { label: 'Thigh-High Boots', value: 'Thigh-High Leather Boots' },
  { label: 'Floating (No Feet)', value: 'Feet fading into smoke' },
];

export const ATTIRE_MATERIALS: SelectOption[] = [
  { label: 'Biomechanical Satin', value: 'Biomechanical Satin' },
  { label: 'Liquid Metal', value: 'Liquid Metal' },
  { label: 'Stained Glass', value: 'Flexible Stained Glass' },
  { label: 'Velvet & Gold', value: 'Deep Velvet with Gold Thread' },
  { label: 'Living Flora', value: 'Living Vines and Flowers' },
  { label: 'Smoke & Shadow', value: 'Solidified Shadow' },
];

export const ATTIRE_PATTERNS: SelectOption[] = [
  { label: 'Sacred Geometry', value: 'Sacred Geometry' },
  { label: 'Floral Fractals', value: 'Floral Fractals' },
  { label: 'Runic Script', value: 'Glowing Runic Script' },
  { label: 'Plain / Solid', value: 'Solid Color' },
  { label: 'Blood Spatter', value: 'Ceremonial Blood Spatter' },
];

export const WEAR_CONDITIONS: SelectOption[] = [
  { label: 'Pristine', value: 'Pristine' },
  { label: 'Battle-Worn', value: 'Battle-Worn' },
  { label: 'Ancient / Dusty', value: 'Ancient and Dusty' },
  { label: 'Burning', value: 'Actively Burning' },
  { label: 'Wet / Soaked', value: 'Soaked with Rain' },
  { label: 'Ethereal Fade', value: 'Fading into Non-Existence' },
];

export const JEWELRY: SelectOption[] = [
  { label: 'None', value: 'no jewelry' },
  { label: 'Body Chains', value: 'Gold Body Chains' },
  { label: 'Choker', value: 'Tight Velvet Choker' },
  { label: 'Pearl Strands', value: 'Strands of Pearls' },
  { label: 'Nose Ring', value: 'Gold Nose Ring and Chain' },
  { label: 'Halo (Floating)', value: 'Floating Metal Halo' },
];

export const SPECTRAL_CONSTANTS: SelectOption[] = [
  { label: 'Gold Theta (Θ) - Stability', value: 'Gold Theta (Θ)' },
  { label: 'Red Phi (Φ) - Rupture', value: 'Red Phi (Φ)' },
  { label: 'Violet Omega (Ω) - Adaptation', value: 'Violet Omega (Ω)' },
  { label: 'Emerald Epsilon (Ε) - Harmony', value: 'Emerald Epsilon (Ε)' },
  { label: 'Azure Lambda (Λ) - Logic', value: 'Azure Lambda (Λ)' },
  { label: 'Silver Sigma (Σ) - Silence', value: 'Silver Sigma (Σ)' },
  { label: 'Obsidian Chi (Χ) - Void', value: 'Obsidian Chi (Χ)' },
];

export const ETIQUETTE_MODES: SelectOption[] = [
  { label: 'Orthodox (Cathedral)', value: 'orthodox' },
  { label: 'Taboo (Corridor)', value: 'taboo_corridor' },
  { label: 'Defiance (Erotic)', value: 'erotic_defiance' },
  { label: 'Shattered (Broken)', value: 'shattered' },
];

export const STANCES: SelectOption[] = [
  { label: 'Perfect Vertical', value: 'The Perfect Vertical' },
  { label: 'Quiet Trespass', value: 'Stance of Quiet Trespass' },
  { label: 'Invitation of Rupture', value: 'Invitation of Rupture' },
  { label: 'Shattered Courtesy', value: 'Shattered Courtesy' },
  { label: 'Forbidden Delta-Gesture', value: 'Forbidden Δ-Gesture' },
  { label: 'Sovereign Aversion', value: 'Sovereign Aversion' },
  { label: 'The Celestial Arc (Firefall)', value: 'The Celestial Arc (Firefall)' },
  { label: 'Suspended Step', value: 'The Suspended Step' },
];

export const CATHEDRAL_ORGANS: SelectOption[] = [
  { label: 'Navigation Organ', value: 'The Navigation Organ' },
  { label: 'Taboo Corridor', value: 'The Taboo Corridor' },
  { label: 'Melting Cathedral (Firefall)', value: 'The Melting Cathedral' },
  { label: 'Library of Silenced', value: 'The Library of Silenced Books' },
  { label: 'Garden of Glass', value: 'The Garden of Glass Flora' },
  { label: 'Autopoietic Heart', value: 'The Autopoietic Heart' },
  { label: 'Veil-Circuit', value: 'The Veil-Circuit Balcony' },
  { label: 'Void-Hive (Nythera)', value: 'Nythera’s Void Hive' },
  { label: 'Honey-Glass Sanctum', value: 'Aurellien’s Honey-Glass Sanctum' },
];

export const LANTERN_BEHAVIORS: SelectOption[] = [
  { label: 'Rising Field', value: 'Rising Field of Lanterns' },
  { label: 'Swarm', value: 'Aggressive Lantern Swarm' },
  { label: 'Dying / Flickering', value: 'Dying, Flickering Lanterns' },
  { label: 'Orbiting', value: 'Lanterns Orbiting the Figure' },
  { label: 'Extinguished', value: 'All Lanterns Extinguished' },
];

export const ART_STYLES: SelectOption[] = [
  { label: 'Lantern-Nouveau (Standard)', value: 'Lantern-Nouveau (Mucha x WLOP)' },
  { label: 'Celestial Firefall', value: 'Apocalyptic MLAOS render, reality-bending heat effects, raw emotional color saturation, catastrophic beauty' },
  { label: 'Celestial Firefall (Apocalyptic)', value: 'Celestial Firefall (High Contrast, Blinding)' },
  { label: 'Gothic Oil', value: 'Dark Gothic Oil Painting' },
  { label: 'Cyber-Cathedral', value: 'Neon Cyber-Cathedral Render' },
  { label: 'Sketch / Etching', value: 'Architectural Sketch/Etching' },
  { label: 'Ethereal Watercolor', value: 'Bleeding Watercolor' },
];

export const LIGHTING: SelectOption[] = [
  { label: 'Cathedral Gloom', value: 'Cathedral Gloom (Low Key)' },
  { label: 'Celestial Firefall', value: 'Celestial Firefall (Blinding Top-Down)' },
  { label: 'Bioluminescent', value: 'Bioluminescent Glow' },
  { label: 'Volumetric God-Rays', value: 'Heavy Volumetric God-Rays' },
  { label: 'Void-Negative', value: 'Void-Negative Lighting' },
  { label: 'Candlelight', value: 'Warm Candlelight' },
];

export const MOODS: SelectOption[] = [
  { label: 'Commanding', value: 'Commanding' },
  { label: 'Serene', value: 'Serene' },
  { label: 'Melancholic', value: 'Melancholic' },
  { label: 'Terrified', value: 'Terrified' },
  { label: 'Ecstatic', value: 'Ecstatic' },
  { label: 'Seductive', value: 'Seductive' },
  { label: 'Rage', value: 'Rage' },
];

export const BACKGROUNDS: SelectOption[] = [
    { label: 'Cathedral Interior', value: 'Cathedral Interior' },
    { label: 'Void', value: 'Infinite Void' },
    { label: 'Garden', value: 'Overgrown Garden' },
    { label: 'Library', value: 'Infinite Library' },
    { label: 'Sky', value: 'Stormy Sky' },
];

// MLAOS: Chromatic Taxonomy
export const CHROMA_PROFILES: SelectOption[] = [
    { label: 'None (Manual Colors)', value: 'none' },
    
    // FIREFALL: CELESTIAL FIREFALL THEME (APOCALYPTIC)
    { label: 'FIREFALL: Ignition-Gold', value: 'FIREFALL: Ignition-Gold' },
    { label: 'FIREFALL: Rupture-Red', value: 'FIREFALL: Rupture-Red' },
    { label: 'FIREFALL: Violet-Storm', value: 'FIREFALL: Violet-Storm' },
    { label: 'FIREFALL: Emerald-Steam', value: 'FIREFALL: Emerald-Steam' },
    { label: 'FIREFALL: Blue-Fracture', value: 'FIREFALL: Blue-Fracture' },
    { label: 'FIREFALL: Bronze-Liquefaction', value: 'FIREFALL: Bronze-Liquefaction' },
    { label: 'FIREFALL: White-Supernova', value: 'FIREFALL: White-Supernova' },
    { label: 'FIREFALL: Core-Breach Orange', value: 'FIREFALL: Core-Breach Orange' },
    { label: 'FIREFALL: Plasma-Arc Cyan', value: 'FIREFALL: Plasma-Arc Cyan' },
    { label: 'FIREFALL: Solar-Shear Yellow', value: 'FIREFALL: Solar-Shear Yellow' },
    { label: 'FIREFALL: Event-Horizon Black', value: 'FIREFALL: Event-Horizon Black' },
    { label: 'FIREFALL: Nebula-Burn Pink', value: 'FIREFALL: Nebula-Burn Pink' },
    { label: 'FIREFALL: Gamma-Ray Violet', value: 'FIREFALL: Gamma-Ray Violet' },
    { label: 'FIREFALL: Neutron-Crush Silver', value: 'FIREFALL: Neutron-Crush Silver' },
    { label: 'FIREFALL: Ion-Storm Indigo', value: 'FIREFALL: Ion-Storm Indigo' },
    { label: 'FIREFALL: Fusion-Pulse Magenta', value: 'FIREFALL: Fusion-Pulse Magenta' },
    { label: 'FIREFALL: Star-Death Crimson', value: 'FIREFALL: Star-Death Crimson' },
    { label: 'FIREFALL: Comet-Tail Teal', value: 'FIREFALL: Comet-Tail Teal' },
    { label: 'FIREFALL: Meteor-Strike Iron', value: 'FIREFALL: Meteor-Strike Iron' },
    { label: 'FIREFALL: Quasar-Beam White', value: 'FIREFALL: Quasar-Beam White' },
    { label: 'FIREFALL: Molten-Choir Gold', value: 'FIREFALL: Molten-Choir Gold' },
    { label: 'FIREFALL: Sky-Rip Vermilion', value: 'FIREFALL: Sky-Rip Vermilion' },
    { label: 'FIREFALL: Glass-Melt Prism', value: 'FIREFALL: Glass-Melt Prism' },
    { label: 'FIREFALL: Ash-Cloud Grey', value: 'FIREFALL: Ash-Cloud Grey' },
    { label: 'FIREFALL: Magma-Vein Red', value: 'FIREFALL: Magma-Vein Red' },
    { label: 'FIREFALL: Electric-Arc Blue', value: 'FIREFALL: Electric-Arc Blue' },
    { label: 'FIREFALL: Thermal-Shock Peach', value: 'FIREFALL: Thermal-Shock Peach' },
    { label: 'FIREFALL: Radiation-Bloom Green', value: 'FIREFALL: Radiation-Bloom Green' },
    { label: 'FIREFALL: Void-Tear Obsidian', value: 'FIREFALL: Void-Tear Obsidian' },
    { label: 'FIREFALL: Corona-Haze Amber', value: 'FIREFALL: Corona-Haze Amber' },
    { label: 'FIREFALL: Singularity-Point Null', value: 'FIREFALL: Singularity-Point Null' },
    { label: 'FIREFALL: Cataclysm-Copper', value: 'FIREFALL: Cataclysm-Copper' },
    { label: 'FIREFALL: Apocalypse-Rose', value: 'FIREFALL: Apocalypse-Rose' },
    { label: 'FIREFALL: Judgment-Platinum', value: 'FIREFALL: Judgment-Platinum' },
    { label: 'FIREFALL: Rapture-Light Pearl', value: 'FIREFALL: Rapture-Light Pearl' },
    { label: 'FIREFALL: Hellfire-Soot', value: 'FIREFALL: Hellfire-Soot' },
    { label: 'FIREFALL: Heaven-Scream Opal', value: 'FIREFALL: Heaven-Scream Opal' },
    { label: 'FIREFALL: Reality-Break Glitch', value: 'FIREFALL: Reality-Break Glitch' },
    { label: 'FIREFALL: Final-Breath Vapor', value: 'FIREFALL: Final-Breath Vapor' },
    { label: 'FIREFALL: Genesis-Spark', value: 'FIREFALL: Genesis-Spark' },

    // I. SOLAR BANDS
    { label: 'SOLAR: Solar Aureate', value: 'Solar Aureate' },
    { label: 'SOLAR: Saffron Bloom', value: 'Saffron Bloom' },
    { label: 'SOLAR: Sunlit Bronze', value: 'Sunlit Bronze' },
    { label: 'SOLAR: Crownfire', value: 'Crownfire' },
    { label: 'SOLAR: Citrine Spiral', value: 'Citrine Spiral' },
    { label: 'SOLAR: Dawn-Flare', value: 'Dawn-Flare' },

    // II. NOCTURNE SPECTRUM
    { label: 'NOCTURNE: Midnight Iridescent', value: 'Midnight Iridescent' },
    { label: 'NOCTURNE: Obsidian Bloom', value: 'Obsidian Bloom' },
    { label: 'NOCTURNE: Indigo Eclipse', value: 'Indigo Eclipse' },
    { label: 'NOCTURNE: Raven-Frost', value: 'Raven-Frost' },
    { label: 'NOCTURNE: Moonless Velvet', value: 'Moonless Velvet' },
    { label: 'NOCTURNE: Starless Smoke', value: 'Starless Smoke' },
    { label: 'NOCTURNE: Nightglass Sheen', value: 'Nightglass Sheen' },

    // III. OCEANIC / TEAL FAMILY
    { label: 'OCEANIC: Tideweave', value: 'Tideweave' },
    { label: 'OCEANIC: Abyss Current', value: 'Abyss Current' },
    { label: 'OCEANIC: Coral Crest', value: 'Coral Crest' },
    { label: 'OCEANIC: Brine Whisper', value: 'Brine Whisper' },
    { label: 'OCEANIC: Aurora Surf', value: 'Aurora Surf' },
    { label: 'OCEANIC: Sapphire Vapor', value: 'Sapphire Vapor' },

    // IV. EARTH / EMERALD FAMILY
    { label: 'EARTH: Verdant Glass', value: 'Verdant Glass' },
    { label: 'EARTH: Mosslight', value: 'Mosslight' },
    { label: 'EARTH: Olive Halo', value: 'Olive Halo' },
    { label: 'EARTH: Forest Shimmer', value: 'Forest Shimmer' },
    { label: 'EARTH: Spring Vellum', value: 'Spring Vellum' },
    { label: 'EARTH: Rooted Ember', value: 'Rooted Ember' },
    { label: 'EARTH: Glade Whisper', value: 'Glade Whisper' },

    // V. ARCANE / PURPLE FAMILY
    { label: 'ARCANE: Amethyst Echo', value: 'Amethyst Echo' },
    { label: 'ARCANE: Orchid Fracture', value: 'Orchid Fracture' },
    { label: 'ARCANE: Ultraviolet Veil', value: 'Ultraviolet Veil' },
    { label: 'ARCANE: Lilac Haze', value: 'Lilac Haze' },
    { label: 'ARCANE: Hex-Violet', value: 'Hex-Violet' },
    { label: 'ARCANE: Prophet’s Bloom', value: 'Prophet’s Bloom' },
    { label: 'ARCANE: Gloaming Whisper', value: 'Gloaming Whisper' },

    // VI. FIRE / CRIMSON SPECTRUM
    { label: 'FIRE: Emberlash', value: 'Emberlash' },
    { label: 'FIRE: Bloodsun', value: 'Bloodsun' },
    { label: 'FIRE: Rosefury', value: 'Rosefury' },
    { label: 'FIRE: Inferno Crown', value: 'Inferno Crown' },
    { label: 'FIRE: Copper Rupture', value: 'Copper Rupture' },
    { label: 'FIRE: Pyre-Silk', value: 'Pyre-Silk' },

    // VII. VOID / ASEMA / NULL
    { label: 'VOID: Nullwhite', value: 'Nullwhite' },
    { label: 'VOID: Paradox Slate', value: 'Paradox Slate' },
    { label: 'VOID: Asema Glass', value: 'Asema Glass' },
    { label: 'VOID: Hollow Bronze', value: 'Hollow Bronze' },
    { label: 'VOID: Echo Black', value: 'Echo Black' },

    // --- EROTIC ETIQUETTE & TABOO STANCE PROFILES ---
    // Soft Provocation
    { label: 'PROVOCATION: Peach Glass Whisper', value: 'Peach Glass Whisper' },
    { label: 'PROVOCATION: Blush Ember', value: 'Blush Ember' },
    { label: 'PROVOCATION: Apricot Veil', value: 'Apricot Veil' },
    { label: 'PROVOCATION: Soft Garnet Drift', value: 'Soft Garnet Drift' },
    { label: 'PROVOCATION: Honey-Rose Diffusion', value: 'Honey-Rose Diffusion' },
    
    // Taboo Geometry
    { label: 'GEOMETRY: Silhouette Saffron', value: 'Silhouette Saffron' },
    { label: 'GEOMETRY: Bronze Meridian', value: 'Bronze Meridian' },
    { label: 'GEOMETRY: Copper Lilt', value: 'Copper Lilt' },
    { label: 'GEOMETRY: Liquid Amber Arc', value: 'Liquid Amber Arc' },
    { label: 'GEOMETRY: Golden Rupture Veil', value: 'Golden Rupture Veil' },
    
    // Corridor of Defiance
    { label: 'DEFIANCE: Violet Pressure', value: 'Violet Pressure' },
    { label: 'DEFIANCE: Amethyst Rift', value: 'Amethyst Rift' },
    { label: 'DEFIANCE: Lavender Fracture', value: 'Lavender Fracture' },
    { label: 'DEFIANCE: Night-Plum Sheen', value: 'Night-Plum Sheen' },
    { label: 'DEFIANCE: Hex-Violet Bloom', value: 'Hex-Violet Bloom' },
    
    // Lantern-Silhouette
    { label: 'SILHOUETTE: Lantern Amber', value: 'Lantern Amber' },
    { label: 'SILHOUETTE: Cinnabar Lantern', value: 'Cinnabar Lantern' },
    { label: 'SILHOUETTE: Honey Lantern Halo', value: 'Honey Lantern Halo' },
    { label: 'SILHOUETTE: Burnished Orange Bloom', value: 'Burnished Orange Bloom' },
    { label: 'SILHOUETTE: Fire-Pearl Lilt', value: 'Fire-Pearl Lilt' },
    
    // Sovereign Defense
    { label: 'DEFENSE: Ice-Rose Authority', value: 'Ice-Rose Authority' },
    { label: 'DEFENSE: Steel-Soft Orchid', value: 'Steel-Soft Orchid' },
    { label: 'DEFENSE: Frost-Violet Meridian', value: 'Frost-Violet Meridian' },
    { label: 'DEFENSE: Silver-Plum Composure', value: 'Silver-Plum Composure' },
    { label: 'DEFENSE: Moon-Glass Whisper', value: 'Moon-Glass Whisper' },
    
    // Shattered Courtesy
    { label: 'SHATTERED: Crimson Halo', value: 'Crimson Halo' },
    { label: 'SHATTERED: Cerise Shatter', value: 'Cerise Shatter' },
    { label: 'SHATTERED: Dusk-Wine Silhouette', value: 'Dusk-Wine Silhouette' },
    { label: 'SHATTERED: Ember-Violet Rupture', value: 'Ember-Violet Rupture' },
    { label: 'SHATTERED: Magenta Flame Curve', value: 'Magenta Flame Curve' },
    
    // Taboo Corridor Signature
    { label: 'SIGNATURE: Prism-Veil Nullpink', value: 'Prism-Veil Nullpink' },
    { label: 'SIGNATURE: Obsidian-Rose Fracture', value: 'Obsidian-Rose Fracture' },
    { label: 'SIGNATURE: Forbidden Orchid', value: 'Forbidden Orchid' },
    { label: 'SIGNATURE: Null-Amber Bloom', value: 'Null-Amber Bloom' },
    { label: 'SIGNATURE: Glass-Crimson Wane', value: 'Glass-Crimson Wane' },
    
    // Cathedral Siren
    { label: 'SIREN: Halo-Copper Silk', value: 'Halo-Copper Silk' },
    { label: 'SIREN: Flame-Ash Crown', value: 'Flame-Ash Crown' },
    { label: 'SIREN: Fire-Wine Meridian', value: 'Fire-Wine Meridian' },
    { label: 'SIREN: Rose-Gold Mirage', value: 'Rose-Gold Mirage' },
    { label: 'SIREN: Lantern-Lure Scarlet', value: 'Lantern-Lure Scarlet' },

    // --- COLLAPSING SURRENDER ---
    { label: 'COLLAPSE: Petal-Fade Ivory', value: 'Petal-Fade Ivory' },
    { label: 'COLLAPSE: Apricot-Down Drift', value: 'Apricot-Down Drift' },
    { label: 'COLLAPSE: Rose-Hush Melt', value: 'Rose-Hush Melt' },
    { label: 'COLLAPSE: Fawn-Relax', value: 'Fawn-Relax' },
    { label: 'COLLAPSE: Vanilla-Sigh', value: 'Vanilla-Sigh' },
    { label: 'COLLAPSE: Honey-Drip', value: 'Honey-Drip' },
    { label: 'COLLAPSE: Cloud-Rose Collapse', value: 'Cloud-Rose Collapse' },
    { label: 'COLLAPSE: Shell-Pearl Unwind', value: 'Shell-Pearl Unwind' },
    { label: 'COLLAPSE: Amber-Kneel Soft', value: 'Amber-Kneel Soft' },
    { label: 'COLLAPSE: Mocha-Quiet', value: 'Mocha-Quiet' },
    { label: 'COLLAPSE: Blush-Crush', value: 'Blush-Crush' },
    { label: 'COLLAPSE: Sienna-Fall', value: 'Sienna-Fall' },
    { label: 'COLLAPSE: Lilac-Slip', value: 'Lilac-Slip' },
    { label: 'COLLAPSE: Ash-Rose Fadeout', value: 'Ash-Rose Fadeout' },
    { label: 'COLLAPSE: Bronze-Drop', value: 'Bronze-Drop' },
    { label: 'COLLAPSE: Teardown Blue', value: 'Teardown Blue' },
    { label: 'COLLAPSE: Olive-Slump', value: 'Olive-Slump' },
    { label: 'COLLAPSE: Wine-Fold', value: 'Wine-Fold' },
    { label: 'COLLAPSE: Candle-Stutter', value: 'Candle-Stutter' },
    { label: 'COLLAPSE: Frosted-Breath Release', value: 'Frosted-Breath Release' },
    { label: 'COLLAPSE: Pink-Quiver', value: 'Pink-Quiver' },
    { label: 'COLLAPSE: Gold-Falter', value: 'Gold-Falter' },
    { label: 'COLLAPSE: Violet-Waver', value: 'Violet-Waver' },
    { label: 'COLLAPSE: Ember-Shiver', value: 'Ember-Shiver' },
    { label: 'COLLAPSE: Teal-Tremor', value: 'Teal-Tremor' },
    { label: 'COLLAPSE: Crimson-Fade Jerk', value: 'Crimson-Fade Jerk' },
    { label: 'COLLAPSE: Opal-Flicker', value: 'Opal-Flicker' },
    { label: 'COLLAPSE: Saffron-Spasm', value: 'Saffron-Spasm' },
    { label: 'COLLAPSE: Midnight-Quake', value: 'Midnight-Quake' },
    { label: 'COLLAPSE: Cerise-Rattle', value: 'Cerise-Rattle' },
    { label: 'COLLAPSE: Spent-Rose', value: 'Spent-Rose' },
    { label: 'COLLAPSE: Extinguished Ember', value: 'Extinguished Ember' },
    { label: 'COLLAPSE: Hearth-Ash', value: 'Hearth-Ash' },
    { label: 'COLLAPSE: Melted-Honey', value: 'Melted-Honey' },
    { label: 'COLLAPSE: Bleached-Blush', value: 'Bleached-Blush' },
    { label: 'COLLAPSE: Dusk-Soaked', value: 'Dusk-Soaked' },
    { label: 'COLLAPSE: Amber-Spentwave', value: 'Amber-Spentwave' },
    { label: 'COLLAPSE: Surrender-Mauve', value: 'Surrender-Mauve' },
    { label: 'COLLAPSE: Pearl-Given', value: 'Pearl-Given' },
    { label: 'COLLAPSE: Shadow-Lull', value: 'Shadow-Lull' },

    // --- DOMINATING ETIQUETTE ---
    { label: 'DOMINION: Crown-Gold', value: 'Crown-Gold' },
    { label: 'DOMINION: Regal Amber', value: 'Regal Amber' },
    { label: 'DOMINION: Imperial Saffron', value: 'Imperial Saffron' },
    { label: 'DOMINION: Lion-Mane Bronze', value: 'Lion-Mane Bronze' },
    { label: 'DOMINION: Empress Citrine', value: 'Empress Citrine' },
    { label: 'DOMINION: Solar-Baroness', value: 'Solar-Baroness' },
    { label: 'DOMINION: Gilded Verdict', value: 'Gilded Verdict' },
    { label: 'DOMINION: Crown-Heliotrope', value: 'Crown-Heliotrope' },
    { label: 'DOMINION: Bronze-Helm', value: 'Bronze-Helm' },
    { label: 'DOMINION: Judge’s Aureole', value: 'Judge’s Aureole' },
    { label: 'DOMINION: Obsidian-Rule', value: 'Obsidian-Rule' },
    { label: 'DOMINION: Raven-Edict', value: 'Raven-Edict' },
    { label: 'DOMINION: Midnight-Mandate', value: 'Midnight-Mandate' },
    { label: 'DOMINION: Ink-Empress', value: 'Ink-Empress' },
    { label: 'DOMINION: Night-Regent', value: 'Night-Regent' },
    { label: 'DOMINION: Noir-Sovereign', value: 'Noir-Sovereign' },
    { label: 'DOMINION: Shadow-Throne', value: 'Shadow-Throne' },
    { label: 'DOMINION: Abyss-Collar', value: 'Abyss-Collar' },
    { label: 'DOMINION: Violet-Authority', value: 'Violet-Authority' },
    { label: 'DOMINION: Obsidian-Crownflare', value: 'Obsidian-Crownflare' },
    { label: 'DOMINION: Platinum Demand', value: 'Platinum Demand' },
    { label: 'DOMINION: Thornline Directive', value: 'Thornline Directive' },
    { label: 'DOMINION: Highglass Authority', value: 'Highglass Authority' },
    { label: 'DOMINION: Sanguine Verdict', value: 'Sanguine Verdict' },
    { label: 'DOMINION: Gilded Pressure', value: 'Gilded Pressure' },
    { label: 'DOMINION: Stormblack Temper', value: 'Stormblack Temper' },
    { label: 'DOMINION: Hallowed Rupture', value: 'Hallowed Rupture' },
    { label: 'DOMINION: Indigo Severity', value: 'Indigo Severity' },
    { label: 'DOMINION: Arterial Focus', value: 'Arterial Focus' },
    { label: 'DOMINION: Copper Dominion', value: 'Copper Dominion' },
    { label: 'DOMINION: Voidseal Command', value: 'Voidseal Command' },
    { label: 'DOMINION: Shatterpink Insistence', value: 'Shatterpink Insistence' },
    { label: 'DOMINION: Solar Lash', value: 'Solar Lash' },
    { label: 'DOMINION: Cerulean Override', value: 'Cerulean Override' },
    { label: 'DOMINION: Obsidian Claim', value: 'Obsidian Claim' },
    { label: 'DOMINION: Imperial Bluerise', value: 'Imperial Bluerise' },
    { label: 'DOMINION: Crown-of-Ruin', value: 'Crown-of-Ruin' },
    { label: 'DOMINION: Sable Projection', value: 'Sable Projection' },
    { label: 'DOMINION: Bloodglass Directive', value: 'Bloodglass Directive' },
    { label: 'DOMINION: The Sovereign Tilt', value: 'The Sovereign Tilt' },
    { label: 'DOMINION: Teal-Directive', value: 'Teal-Directive' },
    { label: 'DOMINION: Ruby-Command', value: 'Ruby-Command' },
    { label: 'DOMINION: Emerald-Law', value: 'Emerald-Law' },
    { label: 'DOMINION: Magenta-Imperative', value: 'Magenta-Imperative' },
    { label: 'DOMINION: Sapphire-Edict', value: 'Sapphire-Edict' },
    { label: 'DOMINION: Amethyst-Commandment', value: 'Amethyst-Commandment' },
    { label: 'DOMINION: Jade-Collar', value: 'Jade-Collar' },
    { label: 'DOMINION: Scarlet-Decree', value: 'Scarlet-Decree' },
    { label: 'DOMINION: Copper-Regal', value: 'Copper-Regal' },
    { label: 'DOMINION: Cyan-Scepter', value: 'Cyan-Scepter' },
    { label: 'DOMINION: Ice-Command', value: 'Ice-Command' },
    { label: 'DOMINION: Frost-Regency', value: 'Frost-Regency' },
    { label: 'DOMINION: Steel-Sovereign', value: 'Steel-Sovereign' },
    { label: 'DOMINION: Chrome-Edict', value: 'Chrome-Edict' },
    { label: 'DOMINION: Glacial-Rule', value: 'Glacial-Rule' },
    { label: 'DOMINION: Slate-Directive', value: 'Slate-Directive' },
    { label: 'DOMINION: Tin-Crown', value: 'Tin-Crown' },
    { label: 'DOMINION: Quartz-Firmament', value: 'Quartz-Firmament' },
    { label: 'DOMINION: Ashen-Edict', value: 'Ashen-Edict' },
    { label: 'DOMINION: Pale-Iron Reign', value: 'Pale-Iron Reign' },

    // --- STANCE-SPECIFIC ---
    { label: 'STANCE: Soft-Cinnamon Trespass', value: 'Soft-Cinnamon Trespass' },
    { label: 'STANCE: Blush-Tilt Ivory', value: 'Blush-Tilt Ivory' },
    { label: 'STANCE: Muted-Rose Edge', value: 'Muted-Rose Edge' },
    { label: 'STANCE: Fawn-Asymmetry', value: 'Fawn-Asymmetry' },
    { label: 'STANCE: Peach-Hairline Crack', value: 'Peach-Hairline Crack' },
    { label: 'STANCE: Dust-Glass Whisper', value: 'Dust-Glass Whisper' },
    { label: 'STANCE: Hazel-Offset', value: 'Hazel-Offset' },
    { label: 'STANCE: Lilac-Low Breach', value: 'Lilac-Low Breach' },
    { label: 'STANCE: Moss-Quiet Tension', value: 'Moss-Quiet Tension' },
    { label: 'STANCE: Vanilla-Fracture Veil', value: 'Vanilla-Fracture Veil' },
    { label: 'STANCE: Crimson-Arc', value: 'Crimson-Arc' },
    { label: 'STANCE: Ember-Lure Gold', value: 'Ember-Lure Gold' },
    { label: 'STANCE: Rose-Rupture Halo', value: 'Rose-Rupture Halo' },
    { label: 'STANCE: Amber-Contrary Meridian', value: 'Amber-Contrary Meridian' },
    { label: 'STANCE: Wine-Invitation', value: 'Wine-Invitation' },
    { label: 'STANCE: Cerise-Vector', value: 'Cerise-Vector' },
    { label: 'STANCE: Ruby-Sway', value: 'Ruby-Sway' },
    { label: 'STANCE: Copper-Open Curve', value: 'Copper-Open Curve' },
    { label: 'STANCE: Lantern-Rift', value: 'Lantern-Rift' },
    { label: 'STANCE: Scarlet-Wave', value: 'Scarlet-Wave' },
    { label: 'STANCE: Shatter-Red Halo', value: 'Shatter-Red Halo' },
    { label: 'STANCE: Violet-Blade Bloom', value: 'Violet-Blade Bloom' },
    { label: 'STANCE: Magenta-Fracture Beam', value: 'Magenta-Fracture Beam' },
    { label: 'STANCE: Gold-Torque', value: 'Gold-Torque' },
    { label: 'STANCE: Obsidian-Crack Rim', value: 'Obsidian-Crack Rim' },
    { label: 'STANCE: Wine-Shear', value: 'Wine-Shear' },
    { label: 'STANCE: Garnet-Break', value: 'Garnet-Break' },
    { label: 'STANCE: Frost-Rupture Edge', value: 'Frost-Rupture Edge' },
    { label: 'STANCE: Bronze-Splinter', value: 'Bronze-Splinter' },
    { label: 'STANCE: Crimson-Vortex', value: 'Crimson-Vortex' },
    { label: 'STANCE: Midnight-Blue Oath', value: 'Midnight-Blue Oath' },
    { label: 'STANCE: Moon-Rose Murmur', value: 'Moon-Rose Murmur' },
    { label: 'STANCE: Indigo-Soft Vow', value: 'Indigo-Soft Vow' },
    { label: 'STANCE: Violet-Festival Glow', value: 'Violet-Festival Glow' },
    { label: 'STANCE: Orchid-Procession', value: 'Orchid-Procession' },
    { label: 'STANCE: Lilac-Censer Light', value: 'Lilac-Censer Light' },
    { label: 'STANCE: Crimson-Sky Surge', value: 'Crimson-Sky Surge' },
    { label: 'STANCE: Blood-Sun Canticle', value: 'Blood-Sun Canticle' },
    { label: 'STANCE: Scarlet-Halo Shout', value: 'Scarlet-Halo Shout' },
    { label: 'STANCE: Ruby-Mutiny Bloom', value: 'Ruby-Mutiny Bloom' },

    // --- SET A: OVERLOAD SCREAM ---
    { label: 'SCREAM: Scream-White Nova', value: 'Scream-White Nova' },
    { label: 'SCREAM: Deafening-Gold Surge', value: 'Deafening-Gold Surge' },
    { label: 'SCREAM: Panic-Violet Flash', value: 'Panic-Violet Flash' },
    { label: 'SCREAM: Rupture-Red Frequency', value: 'Rupture-Red Frequency' },
    { label: 'SCREAM: Overload-Cyan Burst', value: 'Overload-Cyan Burst' },
    { label: 'SCREAM: Hysteria-Pink Flare', value: 'Hysteria-Pink Flare' },
    { label: 'SCREAM: Static-Scream White', value: 'Static-Scream White' },
    { label: 'SCREAM: Blind-Silver Pulse', value: 'Blind-Silver Pulse' },
    { label: 'SCREAM: Terror-Chrome Spike', value: 'Terror-Chrome Spike' },
    { label: 'SCREAM: Shock-Amber Fracture', value: 'Shock-Amber Fracture' },
    { label: 'SCREAM: Voltage-Blue Arc', value: 'Voltage-Blue Arc' },
    { label: 'SCREAM: Fracture-Neon Split', value: 'Fracture-Neon Split' },
    { label: 'SCREAM: Glitch-Magenta Spasm', value: 'Glitch-Magenta Spasm' },
    { label: 'SCREAM: Burn-White Intensity', value: 'Burn-White Intensity' },
    { label: 'SCREAM: Sonic-Yellow Blast', value: 'Sonic-Yellow Blast' },
    { label: 'SCREAM: Quake-Green Shear', value: 'Quake-Green Shear' },
    { label: 'SCREAM: Shatter-Glass Treble', value: 'Shatter-Glass Treble' },
    { label: 'SCREAM: Siren-Red Warning', value: 'Siren-Red Warning' },
    { label: 'SCREAM: Flashbang-Null', value: 'Flashbang-Null' },
    { label: 'SCREAM: Strobe-Indigo Panic', value: 'Strobe-Indigo Panic' },
    { label: 'SCREAM: Surge-Copper Break', value: 'Surge-Copper Break' },
    { label: 'SCREAM: Lightning-Thorn White', value: 'Lightning-Thorn White' },
    { label: 'SCREAM: Blast-Furnace Orange', value: 'Blast-Furnace Orange' },
    { label: 'SCREAM: Solar-Rupture Glare', value: 'Solar-Rupture Glare' },
    { label: 'SCREAM: Void-Scream Black', value: 'Void-Scream Black' },
    { label: 'SCREAM: Prism-Explosion', value: 'Prism-Explosion' },
    { label: 'SCREAM: Radiant-Scourge', value: 'Radiant-Scourge' },
    { label: 'SCREAM: Holy-Fire Overload', value: 'Holy-Fire Overload' },
    { label: 'SCREAM: Acid-Green Burn', value: 'Acid-Green Burn' },
    { label: 'SCREAM: Laser-Violet Cut', value: 'Laser-Violet Cut' },
    { label: 'SCREAM: Plasma-Blue Wash', value: 'Plasma-Blue Wash' },
    { label: 'SCREAM: Arc-Weld Spark', value: 'Arc-Weld Spark' },
    { label: 'SCREAM: Magnesium-Flare', value: 'Magnesium-Flare' },
    { label: 'SCREAM: Nova-Core Collapse', value: 'Nova-Core Collapse' },
    { label: 'SCREAM: Retina-Burn Red', value: 'Retina-Burn Red' },
    { label: 'SCREAM: Gamma-Ray Burst', value: 'Gamma-Ray Burst' },
    { label: 'SCREAM: X-Ray Skeleton', value: 'X-Ray Skeleton' },
    { label: 'SCREAM: Thermal-Shock White', value: 'Thermal-Shock White' },
    { label: 'SCREAM: Neutron-Star Crush', value: 'Neutron-Star Crush' },
    { label: 'SCREAM: Event-Horizon Tear', value: 'Event-Horizon Tear' },

    // --- SET B: COLLAPSE PLEA ---
    { label: 'PLEA: Plea-Pearl Whisper', value: 'Plea-Pearl Whisper' },
    { label: 'PLEA: Begging-Rose Fade', value: 'Begging-Rose Fade' },
    { label: 'PLEA: Bargain-Gold Dust', value: 'Bargain-Gold Dust' },
    { label: 'PLEA: Desperate-Teal Tremor', value: 'Desperate-Teal Tremor' },
    { label: 'PLEA: Kneel-Ash Soften', value: 'Kneel-Ash Soften' },
    { label: 'PLEA: Mercy-Blue Haze', value: 'Mercy-Blue Haze' },
    { label: 'PLEA: Shatter-Prayer White', value: 'Shatter-Prayer White' },
    { label: 'PLEA: Sob-Violet Blur', value: 'Sob-Violet Blur' },
    { label: 'PLEA: Weak-Pulse Peach', value: 'Weak-Pulse Peach' },
    { label: 'PLEA: Surrender-Gray Mist', value: 'Surrender-Gray Mist' },
    { label: 'PLEA: Fawn-Tremble Hope', value: 'Fawn-Tremble Hope' },
    { label: 'PLEA: Blush-Desperation', value: 'Blush-Desperation' },
    { label: 'PLEA: Pale-Offering', value: 'Pale-Offering' },
    { label: 'PLEA: Glass-Tear Break', value: 'Glass-Tear Break' },
    { label: 'PLEA: Whisper-Mint Fade', value: 'Whisper-Mint Fade' },
    { label: 'PLEA: Soft-Crumble Beige', value: 'Soft-Crumble Beige' },
    { label: 'PLEA: Hallow-Bone Quiet', value: 'Hallow-Bone Quiet' },
    { label: 'PLEA: Prayer-Smoke Drift', value: 'Prayer-Smoke Drift' },
    { label: 'PLEA: Submission-Sigh', value: 'Submission-Sigh' },
    { label: 'PLEA: Final-Breath Mist', value: 'Final-Breath Mist' },
    { label: 'PLEA: Wane-Silver Thin', value: 'Wane-Silver Thin' },
    { label: 'PLEA: Fade-Out Russet', value: 'Fade-Out Russet' },
    { label: 'PLEA: Hollow-Chest Blue', value: 'Hollow-Chest Blue' },
    { label: 'PLEA: Empty-Palm Pink', value: 'Empty-Palm Pink' },
    { label: 'PLEA: Trembling-Lip Red', value: 'Trembling-Lip Red' },
    { label: 'PLEA: Wet-Lash Black', value: 'Wet-Lash Black' },
    { label: 'PLEA: Broken-Vow Gold', value: 'Broken-Vow Gold' },
    { label: 'PLEA: Last-Resort Lilac', value: 'Last-Resort Lilac' },
    { label: 'PLEA: Forgiveness-Ivory', value: 'Forgiveness-Ivory' },
    { label: 'PLEA: Penance-Chain Grey', value: 'Penance-Chain Grey' },
    { label: 'PLEA: Sacrifice-Wine', value: 'Sacrifice-Wine' },
    { label: 'PLEA: Martyr-Flame Low', value: 'Martyr-Flame Low' },
    { label: 'PLEA: Grace-Fall Feather', value: 'Grace-Fall Feather' },
    { label: 'PLEA: Abandoned-Altar Dust', value: 'Abandoned-Altar Dust' },
    { label: 'PLEA: Silent-Cry Crystal', value: 'Silent-Cry Crystal' },
    { label: 'PLEA: Shivering-Skin Pale', value: 'Shivering-Skin Pale' },
    { label: 'PLEA: Exposed-Nerve Pink', value: 'Exposed-Nerve Pink' },
    { label: 'PLEA: Bruised-Knee Purple', value: 'Bruised-Knee Purple' },
    { label: 'PLEA: Gasping-Air Clear', value: 'Gasping-Air Clear' },
    { label: 'PLEA: Collapse-Center Black', value: 'Collapse-Center Black' },

    // --- SET C: DOMINANCE ROAR ---
    { label: 'ROAR: Titan-Gold Roar', value: 'Titan-Gold Roar' },
    { label: 'ROAR: Seismic-Obsidian Crush', value: 'Seismic-Obsidian Crush' },
    { label: 'ROAR: Thunder-Indigo Command', value: 'Thunder-Indigo Command' },
    { label: 'ROAR: King-Crimson Bellow', value: 'King-Crimson Bellow' },
    { label: 'ROAR: Emperor-Steel Crash', value: 'Emperor-Steel Crash' },
    { label: 'ROAR: Apex-Solar Flare', value: 'Apex-Solar Flare' },
    { label: 'ROAR: Leviathan-Blue Deep', value: 'Leviathan-Blue Deep' },
    { label: 'ROAR: Warlord-Bronze Slam', value: 'Warlord-Bronze Slam' },
    { label: 'ROAR: Absolute-Zero White', value: 'Absolute-Zero White' },
    { label: 'ROAR: Sovereign-Gravity Black', value: 'Sovereign-Gravity Black' },
    { label: 'ROAR: Dragon-Breath Scorch', value: 'Dragon-Breath Scorch' },
    { label: 'ROAR: Monarch-Red Impact', value: 'Monarch-Red Impact' },
    { label: 'ROAR: Colossus-Stone Weight', value: 'Colossus-Stone Weight' },
    { label: 'ROAR: Storm-Eye Stillness', value: 'Storm-Eye Stillness' },
    { label: 'ROAR: Vortex-Black Pull', value: 'Vortex-Black Pull' },
    { label: 'ROAR: Star-Crush Heavy', value: 'Star-Crush Heavy' },
    { label: 'ROAR: Nova-King Blast', value: 'Nova-King Blast' },
    { label: 'ROAR: Void-Roar Silence', value: 'Void-Roar Silence' },
    { label: 'ROAR: Tyrant-Sun Blaze', value: 'Tyrant-Sun Blaze' },
    { label: 'ROAR: Omega-End Humm', value: 'Omega-End Humm' },
    { label: 'ROAR: Behemoth-Brown Tremor', value: 'Behemoth-Brown Tremor' },
    { label: 'ROAR: Glacier-Crack Blue', value: 'Glacier-Crack Blue' },
    { label: 'ROAR: Volcano-Erupt Core', value: 'Volcano-Erupt Core' },
    { label: 'ROAR: Tsunami-Wall Green', value: 'Tsunami-Wall Green' },
    { label: 'ROAR: Hurricane-Eye Grey', value: 'Hurricane-Eye Grey' },
    { label: 'ROAR: Meteor-Strike Iron', value: 'Meteor-Strike Iron' },
    { label: 'ROAR: God-Fist Gold', value: 'God-Fist Gold' },
    { label: 'ROAR: Law-Hammer Silver', value: 'Law-Hammer Silver' },
    { label: 'ROAR: Judgement-Day Red', value: 'Judgement-Day Red' },
    { label: 'ROAR: Authority-Neon Peak', value: 'Authority-Neon Peak' },
    { label: 'ROAR: Command-Voice Boom', value: 'Command-Voice Boom' },
    { label: 'ROAR: Dominus-Rex Purple', value: 'Dominus-Rex Purple' },
    { label: 'ROAR: Overlord-Shadow Cast', value: 'Overlord-Shadow Cast' },
    { label: 'ROAR: Alpha-Strike Flash', value: 'Alpha-Strike Flash' },
    { label: 'ROAR: Reign-Supreme Cyan', value: 'Reign-Supreme Cyan' },
    { label: 'ROAR: Throne-Room Echo', value: 'Throne-Room Echo' },
    { label: 'ROAR: Crown-Weight Lead', value: 'Crown-Weight Lead' },
    { label: 'ROAR: Scepter-Slam Shock', value: 'Scepter-Slam Shock' },
    { label: 'ROAR: Empire-Dawn Rise', value: 'Empire-Dawn Rise' },
    { label: 'ROAR: Final-Word Echo', value: 'Final-Word Echo' },
];

export const CHROMA_LIBRARY: Record<string, string> = {
    // Soft Provocation
    'Peach Glass Whisper': 'Camera: Soft focus close-up | Gesture: Chin tilted down, eyes looking up | Outfit: Translucent peach glass-silk | Function: Softening the observer\'s resolve | Behavior: Creates gentle allure in micro-inclinations',
    'Blush Ember': 'Camera: Warm candlelight intimacy | Gesture: Hand lightly touching collarbone | Outfit: Dusty rose velvet | Function: Signaling quiet emotional heat | Behavior: Perfect for Quiet Trespass stance',
    'Apricot Veil': 'Camera: Over-shoulder glance | Gesture: Turning away slowly | Outfit: Apricot chiffon layers | Function: Creating distance to invite pursuit | Behavior: Amplifies mild forbidden angles of hips',
    'Soft Garnet Drift': 'Camera: Low angle, focus on drape | Gesture: Letting a sleeve slip slightly | Outfit: Muted garnet silk | Function: Calculated vulnerability | Behavior: Enhances lowered-gaze etiquette',
    'Honey-Rose Diffusion': 'Camera: Backlit by warm lantern | Gesture: Arching back slightly against a pillar | Outfit: Honey-gold lace | Function: Radiating warmth into the cold corridor | Behavior: Ideal for Invitations of Rupture',

    // Taboo Geometry
    'Silhouette Saffron': 'Camera: High contrast silhouette | Gesture: Sharp hip rotation | Outfit: Saffron silk wrapped tight | Function: Emphasizing the geometry of the body | Behavior: Sharpens torso-to-hip angle',
    'Bronze Meridian': 'Camera: Tracking vertical line | Gesture: Arching back | Outfit: Bronze metallic mesh | Function: Highlighting the body\'s centerline | Behavior: Enhances counter-rotation stance',
    'Copper Lilt': 'Camera: Dynamic tilt | Gesture: Weight shift to one leg | Outfit: Flowing copper liquid-metal | Function: Visualizing the twist | Behavior: Emphasizes subtle torso spirals',
    'Liquid Amber Arc': 'Camera: Wide angle low | Gesture: Forbidden Delta-Gesture | Outfit: Amber resin armor (translucent) | Function: Framing the taboo gesture | Behavior: Strengthens the Forbidden Δ-Gesture',
    'Golden Rupture Veil': 'Camera: Close up on torn fabric | Gesture: Pulling veil aside | Outfit: Gold leaf filigree | Function: Revealing rupture points | Behavior: Designed for the middle Forbidden Stance',

    // Corridor of Defiance
    'Violet Pressure': 'Camera: Compressed telephoto | Gesture: Tense stillness | Outfit: Deep violet velvet | Function: Visualizing atmospheric weight | Behavior: Bends Taboo Corridor reflections',
    'Amethyst Rift': 'Camera: Split diopter | Gesture: Breaking symmetry | Outfit: Amethyst crystals | Function: Creating visual discord | Behavior: Ideal for Shattered Courtesy arcs',
    'Lavender Fracture': 'Camera: Broken lens effect | Gesture: Sudden halt | Outfit: Lavender lace | Function: Emphasizing fragility | Behavior: Enhances ceremonial vulnerability postures',
    'Night-Plum Sheen': 'Camera: Low light sheen | Gesture: Slow turn | Outfit: Dark plum satin | Function: Absorbing light | Behavior: Corridor distortions intensify around her',
    'Hex-Violet Bloom': 'Camera: Bloom filter heavy | Gesture: Expanding arms | Outfit: Glowing violet runes | Function: Radiating magical defiance | Behavior: Core palette for erotic etiquette defiance',

    // Lantern-Silhouette
    'Lantern Amber': 'Camera: Backlit warm | Gesture: Haloing self with arms | Outfit: Amber translucent silk | Function: Glowing from within | Behavior: Perfect for aura-based stances',
    'Cinnabar Lantern': 'Camera: Red filtered | Gesture: Sharp profile | Outfit: Cinnabar lacquer armor | Function: Cutting a sharp silhouette | Behavior: Silhouette tension becomes more sensual',
    'Honey Lantern Halo': 'Camera: Soft focus halo | Gesture: Looking over shoulder | Outfit: Honey colored drapes | Function: Softening edges | Behavior: Excels at Ceremony of Unspoken Invitation',
    'Burnished Orange Bloom': 'Camera: Overexposed highlights | Gesture: Leaning forward | Outfit: Burnished orange metal | Function: Catching the light | Behavior: Intensifies hip rotation signals',
    'Fire-Pearl Lilt': 'Camera: Shimmering motion | Gesture: Walking away | Outfit: Pearl with fire opal accents | Function: Leaving a trace | Behavior: Enhances elegance-driven allure',

    // Sovereign Defense
    'Ice-Rose Authority': 'Camera: Low angle power shot | Gesture: Chin raised | Outfit: Frosted rose armor | Function: Establishing dominance | Behavior: Heightens rule-breaking through calm',
    'Steel-Soft Orchid': 'Camera: Cold blue tint | Gesture: Arms crossed loosely | Outfit: Steel mesh and orchid silk | Function: Protecting the core | Behavior: Perfect for taboo etiquette stances',
    'Frost-Violet Meridian': 'Camera: Vertical pan | Gesture: Standing perfectly straight | Outfit: Frost-violet bodysuit | Function: Aligning with the spire | Behavior: Posture appears sharper',
    'Silver-Plum Composure': 'Camera: Static frame | Gesture: Minimal movement | Outfit: Silver and plum brocade | Function: Radiating control | Behavior: Aura reads as “controlled temptation”',
    'Moon-Glass Whisper': 'Camera: Ethereal glow | Gesture: Finger to lips | Outfit: Moon-glass shards | Function: Silencing the viewer | Behavior: Ideal for Forbidden Δ-Gesture contrasts',

    // Shattered Courtesy
    'Crimson Halo': 'Camera: Red ring light | Gesture: Head thrown back | Outfit: Crimson ribbons | Function: Crowning the defiance | Behavior: Core palette for erotic defiance',
    'Cerise Shatter': 'Camera: Fractured prism | Gesture: Breaking the pose | Outfit: Cerise jagged cloth | Function: Visualizing the break | Behavior: Amplifies the “inner arc” of stance III',
    'Dusk-Wine Silhouette': 'Camera: Deep shadow | Gesture: Contorted elegance | Outfit: Dark wine velvet | Function: Hiding the details | Behavior: Elongates silhouette tension',
    'Ember-Violet Rupture': 'Camera: Double exposure | Gesture: Vibrating tension | Outfit: Violet with ember cracks | Function: Showing internal conflict | Behavior: Makes posture feel illicitly potent',
    'Magenta Flame Curve': 'Camera: Following the curve | Gesture: Deep backbend | Outfit: Magenta flame-silk | Function: Emphasizing flexibility | Behavior: Arcs appear dangerously elegant',

    // Taboo Corridor Signature
    'Prism-Veil Nullpink': 'Camera: Rainbow flare | Gesture: Veiling the face | Outfit: Null-pink holographic | Function: Distorting identity | Behavior: Corridor walls ripple',
    'Obsidian-Rose Fracture': 'Camera: High contrast B&W with rose pop | Gesture: Shattering motion | Outfit: Obsidian shards on rose skin | Function: Visualizing damage | Behavior: Sigils glitch around her',
    'Forbidden Orchid': 'Camera: Macro texture | Gesture: Offering | Outfit: Orchid petal texture | Function: Biological allure | Behavior: Perfect for Shattered Courtesy',
    'Null-Amber Bloom': 'Camera: Negative space | Gesture: Void calling | Outfit: Amber void-glass | Function: Inverting light | Behavior: Corridor reflections twist',
    'Glass-Crimson Wane': 'Camera: Fading focus | Gesture: Reaching out | Outfit: Crimson glass | Function: Fading presence | Behavior: Architecture “leans in”',

    // Cathedral Siren
    'Halo-Copper Silk': 'Camera: Divine lighting | Gesture: Beckoning | Outfit: Copper spun silk | Function: Attracting attention | Behavior: Makes etiquette read as invitation',
    'Flame-Ash Crown': 'Camera: Top down | Gesture: Bowing deeply | Outfit: Ash grey with flame tips | Function: Submission as trap | Behavior: Deepens provocative arcs',
    'Fire-Wine Meridian': 'Camera: Center line focus | Gesture: Hands tracking body | Outfit: Wine red liquid | Function: Drawing the eye | Behavior: Silhouette tension rises',
    'Rose-Gold Mirage': 'Camera: Heat haze | Gesture: Shimmering dance | Outfit: Rose gold vapor | Function: Confusing the eye | Behavior: Ideal for invitation stances',
    'Lantern-Lure Scarlet': 'Camera: Spotlight | Gesture: Freezing in light | Outfit: Scarlet moth-silk | Function: Capturing the gaze | Behavior: Strongest erotic etiquette aura',
    
    // CELESTIAL FIREFALL (APOCALYPTIC)
    'FIREFALL: Ignition-Gold': 'Camera: Upward tilt into blinding light | Gesture: Arms wide in acceptance | Outfit: Gold-leaf dissolving into light | Function: Channeling the initial strike | Behavior: Coherence liquefying into pure radiance',
    'FIREFALL: Rupture-Red': 'Camera: Shaking handheld aesthetic | Gesture: Clawing at the chest | Outfit: Torn crimson silk | Function: Visualizing the heart\'s explosion | Behavior: Rupture intensifying into bursts',
    'FIREFALL: Violet-Storm': 'Camera: Dutch angle with lightning | Gesture: Cowering or bracing | Outfit: Violet electrified armor | Function: Surviving the storm | Behavior: Adaptation screaming as it fails',
    'FIREFALL: Emerald-Steam': 'Camera: Foggy and obscured | Gesture: Dissolving silhouette | Outfit: Green vaporous robes | Function: Merging with the heat | Behavior: Harmony boiling into steam',
    'FIREFALL: Blue-Fracture': 'Camera: Shattered lens effect | Gesture: Freezing in fear | Outfit: Blue crystal shards | Function: Reflecting the break | Behavior: Logic fracturing into sharp shards',
    'FIREFALL: Bronze-Liquefaction': 'Camera: Melding floor and feet | Gesture: Sinking | Outfit: Molten bronze | Function: Losing structural integrity | Behavior: Liquefying under thermal stress',
    'FIREFALL: White-Supernova': 'Camera: Overexposed blowout | Gesture: Transcendence | Outfit: Pure white energy | Function: Becoming the event | Behavior: Blinding total release',
    'FIREFALL: Core-Breach Orange': 'Camera: Warning light pulse | Gesture: Shielding eyes | Outfit: Orange hazard-glow | Function: Signaling danger | Behavior: Core stability failing',
    'FIREFALL: Plasma-Arc Cyan': 'Camera: Electric static interference | Gesture: Spasming | Outfit: Cyan lightning bolts | Function: Conducting the surge | Behavior: Arcing across the frame',
    'FIREFALL: Solar-Shear Yellow': 'Camera: Horizontal blur | Gesture: Being pushed back | Outfit: Yellow wind-torn flags | Function: Resisting the blast | Behavior: Shearing force visualized',
    'FIREFALL: Event-Horizon Black': 'Camera: Vignette crushing inward | Gesture: Imploding posture | Outfit: Vantablack void | Function: Absorbing all light | Behavior: Collapsing into singularity',
    'FIREFALL: Nebula-Burn Pink': 'Camera: Cosmic dust swirl | Gesture: Floating | Outfit: Pink stardust mesh | Function: Disintegrating into space | Behavior: Burning into nebula',
    'FIREFALL: Gamma-Ray Violet': 'Camera: X-ray translucency | Gesture: Screaming silently | Outfit: Violet radiation aura | Function: Penetrating the soul | Behavior: Invisible deadly spectrum',
    'FIREFALL: Neutron-Crush Silver': 'Camera: Heavy gravity distortion | Gesture: Crushed to knees | Outfit: Silver dense-matter plate | Function: Enduring immense weight | Behavior: Gravity well collapse',
    'FIREFALL: Ion-Storm Indigo': 'Camera: Magnetic distortion | Gesture: Hair rising | Outfit: Indigo charged particles | Function: Charging the atmosphere | Behavior: Ionization trail',
    'FIREFALL: Fusion-Pulse Magenta': 'Camera: Rhythmic throbbing | Gesture: Heartbeat sync | Outfit: Magenta reactor core | Function: Powering the cataclysm | Behavior: Fusion reaction pulsing',
    'FIREFALL: Star-Death Crimson': 'Camera: Dying light red shift | Gesture: Final exhale | Outfit: Crimson funeral shroud | Function: Mourning the star | Behavior: Red giant expansion',
    'FIREFALL: Comet-Tail Teal': 'Camera: Motion streak | Gesture: Falling forward | Outfit: Teal vapor trail | Function: Trailing debris | Behavior: Sublimating ice',
    'FIREFALL: Meteor-Strike Iron': 'Camera: Impact crater POV | Gesture: Bracing for impact | Outfit: Iron meteoric rock | Function: The moment of contact | Behavior: Kinetic energy release',
    'FIREFALL: Quasar-Beam White': 'Camera: Narrow beam focus | Gesture: Pointing | Outfit: Focused white laser | Function: Directing the destruction | Behavior: Relativistic jet',
    'FIREFALL: Molten-Choir Gold': 'Camera: Melting gold texture | Gesture: Singing in pain | Outfit: Dripping gold vestments | Function: The choir dissolving | Behavior: Sacred melody liquefying',
    'FIREFALL: Sky-Rip Vermilion': 'Camera: Looking up at tear | Gesture: Reaching for the rip | Outfit: Vermilion sky-fabric | Function: Tearing the firmament | Behavior: Reality fabric rending',
    'FIREFALL: Glass-Melt Prism': 'Camera: Refractive distortion | Gesture: Shielding face | Outfit: Molten glass drips | Function: Transparent failure | Behavior: Prismatic meltdown',
    'FIREFALL: Ash-Cloud Grey': 'Camera: Particle choke | Gesture: Coughing/Choking | Outfit: Grey ash layers | Function: Aftermath texture | Behavior: Volcanic winter',
    'FIREFALL: Magma-Vein Red': 'Camera: Subdermal glow focus | Gesture: Straining muscles | Outfit: Rock with red cracks | Function: Internal pressure | Behavior: Veins bursting with lava',
    'FIREFALL: Electric-Arc Blue': 'Camera: Tesla coil arcing | Gesture: Rigid shock | Outfit: Blue spark gap | Function: High voltage bridge | Behavior: Uncontrolled discharge',
    'FIREFALL: Thermal-Shock Peach': 'Camera: Heat haze shimmering | Gesture: Fanning self | Outfit: Peach heat-signature | Function: Overheating | Behavior: Thermal expansion',
    'FIREFALL: Radiation-Bloom Green': 'Camera: Geiger counter grain | Gesture: Sickness | Outfit: Toxic green glow | Function: Radioactive decay | Behavior: Cherenkov radiation',
    'FIREFALL: Void-Tear Obsidian': 'Camera: Negative space tear | Gesture: Stepping into nothing | Outfit: Obsidian shards | Function: Reality leak | Behavior: Existence failure',
    'FIREFALL: Corona-Haze Amber': 'Camera: Sun-glare wash | Gesture: Squinting | Outfit: Amber solar flare | Function: Solar atmosphere | Behavior: Coronal mass ejection',
    'FIREFALL: Singularity-Point Null': 'Camera: Fisheye distortion | Gesture: Curled into ball | Outfit: Null-texture | Function: Infinite density | Behavior: Spaghettification',
    'FIREFALL: Cataclysm-Copper': 'Camera: Sepia tone destruction | Gesture: Witnessing | Outfit: Copper rust | Function: Ancient apocalypse | Behavior: Oxidation acceleration',
    'FIREFALL: Apocalypse-Rose': 'Camera: Beautiful destruction | Gesture: Embracing the end | Outfit: Rose petal ash | Function: Romanticizing the end | Behavior: Floral extinction',
    'FIREFALL: Judgment-Platinum': 'Camera: Cold divine light | Gesture: Kneeling in judgment | Outfit: Platinum chains | Function: Divine sentence | Behavior: Absolute purity burn',
    'FIREFALL: Rapture-Light Pearl': 'Camera: Ascension lift | Gesture: Floating upward | Outfit: Pearl ascendant robes | Function: Being taken | Behavior: Rapturous disintegration',
    'FIREFALL: Hellfire-Soot': 'Camera: Dark and gritty | Gesture: Crawling | Outfit: Blackened soot rags | Function: Surviving the fire | Behavior: Carbonization',
    'FIREFALL: Heaven-Scream Opal': 'Camera: Iridescent fracture | Gesture: Screaming at sky | Outfit: Opal angelic armor | Function: Celestial war | Behavior: Angelic chord breaking',
    'FIREFALL: Reality-Break Glitch': 'Camera: Digital artifacting | Gesture: T-pose glitch | Outfit: Pixelated texture | Function: Simulation crash | Behavior: Buffer overflow',
    'FIREFALL: Final-Breath Vapor': 'Camera: Macro on breath | Gesture: Exhaling | Outfit: Vaporous white | Function: Life leaving | Behavior: Evaporation',
    'FIREFALL: Genesis-Spark': 'Camera: Macro spark | Gesture: Fetal position | Outfit: Primordial soup | Function: New beginning | Behavior: Big Bang ignition',
};
